mail:
  host: smtp.gmail.com
  port: 587
  protocol: smtp
  default-encoding: UTF-8
  username: moonssjoy@gmail.com
  password: iwpgbzwnszcvzsbl
  smtp:
    start-tls-enable: true
    auth: true
  spring:
    datasource:
      url : jdbc:mysql://playdatafinalproject.cd1jlzm6mpyt.ap-northeast-2.rds.amazonaws.com:3306/shelter?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
      username : finalproject
      password : playdata1212
      driver-class-name: com.mysql.cj.jdbc.Driver
    mybatis:
      type-aliases-package: com.finalproject
      mapper-locations: mybatis/mapper/**/*.xml

